services:
  feather-book-backend:
    image: feather-book-backend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker